Fiction2/Fiction2/Models/MainViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fiction2.Models
{
    public class MainViewModel
    {
        public IList<Book> Books { get; set; }
        public IList<Book> MyBooks { get; set; }
        public IList<Group> Groups { get; set; }
        public IList<Group> MyGroups { get; set; }
      
    }
}

Fiction2/Fiction2/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fiction2.Data;
using Fiction2.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fiction2.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> userManager;

        public BooksController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            this.db = db;
            this.userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => userManager.GetUserAsync(HttpContext.User);

        public Book Book { get; set; }
        public IList<Post> Posts { get; set; }

        public async Task<IActionResult> Write(int id)
        {
            Book = await db.Books.Include(b => b.Group).Include(b => b.Posts).ThenInclude(p => p.ApplicationUser).SingleOrDefaultAsync(i => i.Id == id);
            Posts = Book.Posts.OrderByDescending(s => s.Id).ToList();
            BookViewModel bookViewModel = new BookViewModel() { Book = Book, Posts = Posts };
            return View(bookViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Save(BookViewModel bookModel)
        {
            bookModel.Book.LastUpdated = DateTime.Now;
            var user = await GetCurrentUserAsync();
            bookModel.Book.LastUpdatedBy = user.UserName;
            db.Attach(bookModel.Book).State = EntityState.Modified;
            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {

                throw new Exception("Book not found");
            }
            return RedirectToAction("Write", new { id = bookModel.Book.Id});
        }

        [HttpPost]
        public async Task<IActionResult> Post(BookViewModel bookModel, int BookId)
        {
            var user = await GetCurrentUserAsync();
            Book Book = await db.Books.SingleOrDefaultAsync(i => i.Id == BookId);
            bookModel.Post.ApplicationUser = user;
            bookModel.Post.Date = DateTime.Now;
            bookModel.Post.Book = Book;
            
            db.Posts.Add(bookModel.Post);
            await db.SaveChangesAsync();
            return RedirectToAction("Write", new { id = BookId });
        }

        public async Task<IActionResult> Read(int id)
        {
            Book = await db.Books.Include(c => c.Group).ThenInclude(x => x.GroupMembers).ThenInclude(g => g.ApplicationUser).SingleOrDefaultAsync(i => i.Id == id);
            return View(Book);
        }
    }
}

Fiction2/Fiction2/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fiction2.Data;
using Fiction2.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fiction2.Controllers
{
    public class MainController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> userManager;

        public MainController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            this.db = db;
            this.userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => userManager.GetUserAsync(HttpContext.User);

        public IList<Book> Books { get; set; }
        public IList<Book> MyBooks { get; set; }
        public IList<Group> Groups { get; set; }
        public IList<Group> MyGroups { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

        public async Task<IActionResult> Main(string SearchString)
        {

            var user = await GetCurrentUserAsync();
            IQueryable<Book> books = db.Books;
            if (!string.IsNullOrEmpty(SearchString))
            {
                books = books.Where(b => b.Name.Contains(SearchString));
            }
            Books = await books.ToListAsync();
            MyBooks = new List<Book>();
            MyGroups = await db.Groups.Where(emp => emp.GroupMembers.Any(r => r.ApplicationUserId == user.Id)).Include(g => g.Books).ToListAsync();
            foreach (Group group in MyGroups)
            {
                foreach (Book book in group.Books)
                {
                    MyBooks.Add(book);
                }
            }
            MainViewModel mainViewModel = new MainViewModel() { Books = Books, MyBooks = MyBooks, MyGroups = MyGroups };
            return View(mainViewModel);
        }

        [HttpPost]
        public string Main(string searchString, bool notUsed)
        {
            return "From [HttpPost]Main: filter on " + searchString;
        }

        public async Task<IActionResult> BrowseGroups(string SearchString)
        {
            var user = await GetCurrentUserAsync();
            IQueryable<Group> groups =  db.Groups.Include(c => c.GroupMembers).ThenInclude(x => x.ApplicationUser); 
            if (!string.IsNullOrEmpty(SearchString))
            {
                groups = groups.Where(b => b.Name.Contains(SearchString));
            }
            Groups = await groups.ToListAsync();
            
            MyBooks = new List<Book>();
            MyGroups = await db.Groups.Where(emp => emp.GroupMembers.Any(r => r.ApplicationUserId == user.Id)).Include(g => g.Books).ToListAsync();
            foreach (Group group in MyGroups)
            {
                foreach (Book book in group.Books)
                {
                    MyBooks.Add(book);
                }
            }

            MainViewModel mainViewModel = new MainViewModel() { Groups = Groups, MyBooks = MyBooks, MyGroups = MyGroups };
            return View(mainViewModel);
        }

        [HttpPost]
        public string BrowseGroups(string searchString, bool notUsed)
        {
            return "From [HttpPost]BrowseGroups: filter on " + searchString;
        }

        public async Task<IActionResult> Profile(string id)
        {
            IList<ApplicationUser> users = await userManager.Users.Where(u => u.Id == id).Include(u => u.GroupMembers).ToListAsync();
            var user = users[0];
            IList<Book> MyBooks = new List<Book>();
            IList<Group> MyGroups = await db.Groups.Where(emp => emp.GroupMembers.Any(r => r.ApplicationUserId == user.Id)).Include(g => g.Books).ToListAsync();
            foreach (Group group in MyGroups)
            {
                foreach (Book book in group.Books)
                {
                    MyBooks.Add(book);
                }
            }
            UserViewModel userViewModel = new UserViewModel() { ApplicationUser = user, Books = MyBooks};
            return View(userViewModel);
        }
    }
}

Fiction2/Fiction2/Controllers/MyPagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Fiction2.Data;
using Fiction2.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fiction2.Controllers
{
    public class MyPagesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> userManager;

        public MyPagesController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            this.db = db;
            this.userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => userManager.GetUserAsync(HttpContext.User);

        public IList<Book> Books { get; set; }
        public IList<Group> Groups { get; set; }

        public async Task<IActionResult> MyBooks()
        {
            Books = new List<Book>();
            var user = await GetCurrentUserAsync();
            Groups = await db.Groups.Where(emp => emp.GroupMembers.Any(r => r.ApplicationUserId == user.Id)).Include(g => g.Books).ToListAsync();
            foreach (Group group in Groups)
            {
                foreach (Book book in group.Books)
                {
                    Books.Add(book);
                }
            }

            MainViewModel mainViewModel = new MainViewModel() { MyBooks = Books, MyGroups = Groups};
            return View(mainViewModel);
        }

        public async Task<IActionResult> MyGroups()
        {
            var user = await GetCurrentUserAsync();
            Groups = await db.Groups.Where(emp => emp.GroupMembers.Any(r => r.ApplicationUserId == user.Id)).Include(c => c.GroupMembers).ThenInclude(x => x.ApplicationUser).ToListAsync();
            return View(Groups);
        }

        [HttpPost]
        public async Task<IActionResult> CreateGroup(Group group)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                var user = await GetCurrentUserAsync();
                //Group group = new Group { Name = Input.Name, Description = Input.Description };
                GroupMember groupMember = new GroupMember { ApplicationUser = user, Group = group };
                db.Groups.Add(group);
                db.GroupMembers.Add(groupMember);
                await db.SaveChangesAsync();
                return RedirectToAction("MyGroups");
            }

        }

        [HttpPost]
        public async Task<IActionResult> CreateBook(CreateBookViewModel bookModel, IFormFile Image)
        {
            byte[] temp = null;
            
                if (Image.Length > 0)
                {
                    using (var stream = new MemoryStream())
                    {
                        await Image.CopyToAsync(stream);
                        temp = stream.ToArray();
                    }
                }
            

            IList<Group> groups = await db.Groups.Where(g => g.Id == bookModel.GroupId).ToListAsync();
            DateTime date = DateTime.Now;
            var user = await GetCurrentUserAsync();
            string updatedBy = user.UserName;
            Book book = new Book { Name = bookModel.Name, Description = bookModel.Description, Image = temp, Group = groups[0], LastUpdated = date, LastUpdatedBy = updatedBy };
            db.Books.Add(book);
            await db.SaveChangesAsync();
            return RedirectToAction("MyBooks");
        }

        private bool isUsers;
        public Group Group { get; set; }

        public async Task<IActionResult> ViewGroup(int id)
        {
            isUsers = true;
            var user = await GetCurrentUserAsync();
            Group = await db.Groups.Include(c => c.GroupMembers).ThenInclude(x => x.ApplicationUser).Include(c => c.JoinRequests).ThenInclude(x => x.ApplicationUser).SingleOrDefaultAsync(i => i.Id == id);
            Books = await db.Books.Where(b => b.Group.Id == Group.Id).ToListAsync();
            int count = 0;
            foreach (var item in Group.GroupMembers)
            {
                if (item.ApplicationUserId == user.Id)
                {
                    count++;
                }
            }
            if (count > 0)
            {
                isUsers = true;
            }
            else
            {
                isUsers = false;
            }
            GroupViewModel groupViewModel = new GroupViewModel() { Id = Group.Id, Name = Group.Name, Description = Group.Description, Books = Books, GroupMembers = Group.GroupMembers, JoinRequests = Group.JoinRequests, IsUsers = isUsers };
            return View(groupViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> JoinGroup(int Id)
        {
            var user = await GetCurrentUserAsync();
            Group Group = await db.Groups.SingleOrDefaultAsync(i => i.Id == Id);
            JoinRequest joinRequest = new JoinRequest { ApplicationUser = user, Group = Group };
            db.JoinRequests.Add(joinRequest);
            await db.SaveChangesAsync();
            return RedirectToAction("BrowseGroups", "Main");
        }

        [HttpPost]
        public async Task<IActionResult> AcceptRequest(int Id, string UserId)
        {
            IList<ApplicationUser> users = await userManager.Users.Where(u => u.Id == UserId).ToListAsync();
            var user = users[0];
            Group Group = await db.Groups.SingleOrDefaultAsync(i => i.Id == Id);
            GroupMember groupMember = new GroupMember { ApplicationUser = user, Group = Group };
            JoinRequest joinRequest = await db.JoinRequests.FindAsync(UserId, Id);
            db.GroupMembers.Add(groupMember);
            db.JoinRequests.Remove(joinRequest);
            await db.SaveChangesAsync();
            return RedirectToAction("ViewGroup", new { id = Id });
        }

        [HttpPost]
        public async Task<IActionResult> DeclineRequest(int Id, string UserId)
        {
            IList<ApplicationUser> users = await userManager.Users.Where(u => u.Id == UserId).ToListAsync();
            var user = users[0];
            Group Group = await db.Groups.SingleOrDefaultAsync(i => i.Id == Id);
            JoinRequest joinRequest = await db.JoinRequests.FindAsync(UserId, Id);
            db.JoinRequests.Remove(joinRequest);
            await db.SaveChangesAsync();
            return RedirectToAction("ViewGroup", new { id = Id });
        }

    }
}

Fiction2/Fiction2/Views/Main/BrowseGroups.cshtml
@model Fiction2.Models.MainViewModel

@{
    ViewData["Title"] = "BrowseGroups";
}

<div class="row" style="margin-top: 50px; ">
    <div class="col-md-9">
        <h2 style="color: #659EC7;">Browse Groups</h2>
        <div>
            <form>
                <div asp-validation-summary="All" class="text-danger"></div>
                <div style="width: 100%; height: 80px;" class="input-group">
                    <input  name="SearchString" style="width: 60%; height: 50%" class="form-control" placeholder="Search" />
                    <span class="input-group-append">
                        <button style="height: 50%" type="submit" class="btn btn-default"><img src="~/images/search.png" style="width: 20px;"></button>
                    </span>
                    <span class="text-danger"></span>
                </div>
            </form>
        </div>



        @foreach (var group in Model.Groups)
        {
            <div class="groups">
                <a asp-controller="MyPages" asp-action="ViewGroup" asp-route-id="@group.Id" style="font-size: 160%; font-weight: bold; color: black;">@group.Name</a>
                <p>@group.Description</p>
                <h4 style="float: left; font-weight: bold">Members: </h4>
                @foreach (var member in @group.GroupMembers)
                {
                    <p class="members-list">@member.ApplicationUser.UserName</p>
                }
            </div>
            <br>
        }
    </div>

    <div class="col-md-3 aside">
        <h4>MY BOOKS</h4>
        <div class="list">
            @if (Model.MyBooks.Count > 0)
            {
                @foreach (var book in Model.MyBooks)
                {
                    <a asp-controller="Books" asp-action="Write" asp-route-id="@book.Id">@book.Name</a>
                    <br>
                }
            }
            else
            {
                <p>No Books Yet</p>
            }

        </div>
        <h4>MY GROUPS</h4>
        <div class="list">
            @if (Model.MyGroups.Count > 0)
            {
                @foreach (var group in Model.MyGroups)
                {
                    <a asp-controller="MyPages" asp-action="ViewGroup" asp-route-id="@group.Id">@group.Name</a>
                    <br>
                }
            }
            else
            {
                <p>No Groups Yet</p>
            }
        </div>
    </div>
</div>

Fiction2/Fiction2/Views/Main/Main.cshtml
@model Fiction2.Models.MainViewModel

@{
    ViewData["Title"] = "Main";
}

<div style="margin-top: 80px;" class="row">
    <div class="col-md-9">
        <form asp-controller="Main" asp-action="Main" method="get">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div style="width: 140%; margin-left: 10%; height: 80px;" class="input-group">
                <input name="SearchString" style="width: 50%; height: 50%" class="form-control" placeholder="Search" />
                <span class="input-group-append">
                    <button style="height: 50%" type="submit" class="btn btn-default" value="Filter"><img src="~/images/search.png" style="width: 20px;"></button>
                </span>
                <span class="text-danger"></span>
            </div>
        </form>

        <div class="books">
            @foreach (var book in Model.Books)
            {

                var base64 = Convert.ToBase64String(book.Image);
                var imgSrc = String.Format("data:image/png;base64,{0}", base64);


                <div class="thumbnail">
                    <a asp-controller="Books" asp-action="Read" asp-route-id="@book.Id">
                        <img src="@imgSrc" alt="Lights" style="width:80%; height:100%;">
                        <div class="caption" style="text-align: center; padding: 10px 0;">
                            <p><b>@book.Name</b></p>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>

    <div class="col-md-3 aside">
        <h4>MY BOOKS</h4>
        <div class="list">
            @if (Model.MyBooks.Count > 0)
            {
                @foreach (var book in Model.MyBooks)
                {
                    <a asp-controller="Books" asp-action="Write" asp-route-id="@book.Id">@book.Name</a>
                    <br>
                }
            }
            else
            {
                <p>No Books Yet</p>
            }

        </div>
        <h4>MY GROUPS</h4>
        <div class="list">
            @if (Model.MyGroups.Count > 0)
            {
                @foreach (var group in Model.MyGroups)
                {
                    <a asp-controller="MyPages" asp-action="ViewGroup" asp-route-id="@group.Id">@group.Name</a>
                    <br>
                }
            }
            else
            {
                <p>No Groups Yet</p>
            }
        </div>
    </div>


</div>

Fiction2/Fiction2/Views/Main/Profile.cshtml
@model Fiction2.Models.UserViewModel

@{
    ViewData["Title"] = "Profile";
}

<div class="container" style="margin-top: 60px;">
    @{
        var base64 = Convert.ToBase64String(Model.ApplicationUser.Image);
        var imgSrc = String.Format("data:image/png;base64,{0}", base64); 
     }
    <img class="img-rounded" id="viewImage" src="@imgSrc" alt="ICON" style="float: left; width: 10%; margin-right: 1%;">
    <h2 style="color: #659EC7; font-size: 300%; margin-bottom: 0;">@Model.ApplicationUser.FullName</h2>
    <em style="font-size: 125%; text-decoration: underline">@Model.ApplicationUser.UserName</em>
    <p style="font-size: 125%;">@Model.ApplicationUser.About</p>
    <hr />


    <div class="row">
        <div class="col-md-4">
            <h4 style="font-weight: bold; font-size: 175%;">Groups</h4>

            @foreach (var member in Model.ApplicationUser.GroupMembers)
            {
                <p class="members-list" style="float: none; font-size: 150%;">@member.Group.Name</p>
            }


        </div>
        <div class="col-md-8" style="border-left: 1px solid #888888; height: 450px;">
            <h4 style="font-weight: bold; font-size: 175%;">Books</h4>
            <div class="books" style="margin-left: 3%;">

                @foreach (var book in Model.Books)
                {

                    var _base64 = Convert.ToBase64String(book.Image);
                    var _imgSrc = String.Format("data:image/png;base64,{0}", _base64);
                   
                    <div class="thumbnail">
                        <a asp-controller="Books" asp-action="Read" asp-route-id="@book.Id">
                            <img src="@_imgSrc" alt="Lights" style="width:90%; height: 90%;">
                            <div class="caption" style="text-align: center; padding: 10px 0;">
                                <p><b>@book.Name</b></p>
                            </div>
                        </a>
                    </div>
                }

            </div>
        </div>
    </div>
</div>